OUTROOT ?= .

GO ?= go
GO_LINT ?= golangci-lint

.PHONY: build server client
build: server client
server client:
	$(GO) build -v -o $(OUTROOT)/bin/$@ ./cmd/$@

.PHONY: test
test:
	$(GO) test -v -race ./...

.PHONY: fmt
fmt:
	$(GO) fmt ./...

.PHONY: tidy
tidy:
	$(GO) mod tidy

.PHONY: check-gen
check-gen: OUTROOT := .
check-gen: fmt tidy
	git diff --exit-code

.PHONY: lint
lint:
	$(GO_LINT) run -v ./...
