// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: jobworker.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GetJobResponse_Status int32

const (
	GetJobResponse_UNKNOWN   GetJobResponse_Status = 0
	GetJobResponse_RUNNING   GetJobResponse_Status = 1
	GetJobResponse_COMPLETED GetJobResponse_Status = 2
	GetJobResponse_STOPPED   GetJobResponse_Status = 3
	// the command either failed to start (it never ran) or it started
	// but was terminated unexpectedly (probably signaled)
	GetJobResponse_FAILED GetJobResponse_Status = 4
	// the command has not started yet
	GetJobResponse_PENDING GetJobResponse_Status = 5
)

var GetJobResponse_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "RUNNING",
	2: "COMPLETED",
	3: "STOPPED",
	4: "FAILED",
	5: "PENDING",
}

var GetJobResponse_Status_value = map[string]int32{
	"UNKNOWN":   0,
	"RUNNING":   1,
	"COMPLETED": 2,
	"STOPPED":   3,
	"FAILED":    4,
	"PENDING":   5,
}

func (x GetJobResponse_Status) String() string {
	return proto.EnumName(GetJobResponse_Status_name, int32(x))
}

func (GetJobResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4fc5f638932919ca, []int{6, 0}
}

type CommandSpec struct {
	Command              string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args                 []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Env                  []string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty"`
	Dir                  string   `protobuf:"bytes,4,opt,name=dir,proto3" json:"dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandSpec) Reset()         { *m = CommandSpec{} }
func (m *CommandSpec) String() string { return proto.CompactTextString(m) }
func (*CommandSpec) ProtoMessage()    {}
func (*CommandSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fc5f638932919ca, []int{0}
}
func (m *CommandSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandSpec.Unmarshal(m, b)
}
func (m *CommandSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandSpec.Marshal(b, m, deterministic)
}
func (m *CommandSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandSpec.Merge(m, src)
}
func (m *CommandSpec) XXX_Size() int {
	return xxx_messageInfo_CommandSpec.Size(m)
}
func (m *CommandSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandSpec.DiscardUnknown(m)
}

var xxx_messageInfo_CommandSpec proto.InternalMessageInfo

func (m *CommandSpec) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *CommandSpec) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *CommandSpec) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *CommandSpec) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

type StartJobRequest struct {
	Command              *CommandSpec `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StartJobRequest) Reset()         { *m = StartJobRequest{} }
func (m *StartJobRequest) String() string { return proto.CompactTextString(m) }
func (*StartJobRequest) ProtoMessage()    {}
func (*StartJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fc5f638932919ca, []int{1}
}
func (m *StartJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartJobRequest.Unmarshal(m, b)
}
func (m *StartJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartJobRequest.Marshal(b, m, deterministic)
}
func (m *StartJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartJobRequest.Merge(m, src)
}
func (m *StartJobRequest) XXX_Size() int {
	return xxx_messageInfo_StartJobRequest.Size(m)
}
func (m *StartJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartJobRequest proto.InternalMessageInfo

func (m *StartJobRequest) GetCommand() *CommandSpec {
	if m != nil {
		return m.Command
	}
	return nil
}

type StartJobResponse struct {
	JobUuid              string   `protobuf:"bytes,1,opt,name=job_uuid,json=jobUuid,proto3" json:"job_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartJobResponse) Reset()         { *m = StartJobResponse{} }
func (m *StartJobResponse) String() string { return proto.CompactTextString(m) }
func (*StartJobResponse) ProtoMessage()    {}
func (*StartJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fc5f638932919ca, []int{2}
}
func (m *StartJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartJobResponse.Unmarshal(m, b)
}
func (m *StartJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartJobResponse.Marshal(b, m, deterministic)
}
func (m *StartJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartJobResponse.Merge(m, src)
}
func (m *StartJobResponse) XXX_Size() int {
	return xxx_messageInfo_StartJobResponse.Size(m)
}
func (m *StartJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartJobResponse proto.InternalMessageInfo

func (m *StartJobResponse) GetJobUuid() string {
	if m != nil {
		return m.JobUuid
	}
	return ""
}

type StopJobRequest struct {
	JobUuid              string   `protobuf:"bytes,1,opt,name=job_uuid,json=jobUuid,proto3" json:"job_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopJobRequest) Reset()         { *m = StopJobRequest{} }
func (m *StopJobRequest) String() string { return proto.CompactTextString(m) }
func (*StopJobRequest) ProtoMessage()    {}
func (*StopJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fc5f638932919ca, []int{3}
}
func (m *StopJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopJobRequest.Unmarshal(m, b)
}
func (m *StopJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopJobRequest.Marshal(b, m, deterministic)
}
func (m *StopJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopJobRequest.Merge(m, src)
}
func (m *StopJobRequest) XXX_Size() int {
	return xxx_messageInfo_StopJobRequest.Size(m)
}
func (m *StopJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopJobRequest proto.InternalMessageInfo

func (m *StopJobRequest) GetJobUuid() string {
	if m != nil {
		return m.JobUuid
	}
	return ""
}

type StopJobResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopJobResponse) Reset()         { *m = StopJobResponse{} }
func (m *StopJobResponse) String() string { return proto.CompactTextString(m) }
func (*StopJobResponse) ProtoMessage()    {}
func (*StopJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fc5f638932919ca, []int{4}
}
func (m *StopJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopJobResponse.Unmarshal(m, b)
}
func (m *StopJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopJobResponse.Marshal(b, m, deterministic)
}
func (m *StopJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopJobResponse.Merge(m, src)
}
func (m *StopJobResponse) XXX_Size() int {
	return xxx_messageInfo_StopJobResponse.Size(m)
}
func (m *StopJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopJobResponse proto.InternalMessageInfo

type GetJobRequest struct {
	JobUuid              string   `protobuf:"bytes,1,opt,name=job_uuid,json=jobUuid,proto3" json:"job_uuid,omitempty"`
	WithLogs             bool     `protobuf:"varint,2,opt,name=with_logs,json=withLogs,proto3" json:"with_logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobRequest) Reset()         { *m = GetJobRequest{} }
func (m *GetJobRequest) String() string { return proto.CompactTextString(m) }
func (*GetJobRequest) ProtoMessage()    {}
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fc5f638932919ca, []int{5}
}
func (m *GetJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobRequest.Unmarshal(m, b)
}
func (m *GetJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobRequest.Marshal(b, m, deterministic)
}
func (m *GetJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobRequest.Merge(m, src)
}
func (m *GetJobRequest) XXX_Size() int {
	return xxx_messageInfo_GetJobRequest.Size(m)
}
func (m *GetJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobRequest proto.InternalMessageInfo

func (m *GetJobRequest) GetJobUuid() string {
	if m != nil {
		return m.JobUuid
	}
	return ""
}

func (m *GetJobRequest) GetWithLogs() bool {
	if m != nil {
		return m.WithLogs
	}
	return false
}

type GetJobResponse struct {
	Command *CommandSpec          `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Status  GetJobResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=jobworker.GetJobResponse_Status" json:"status,omitempty"`
	// equals -1 if the command execution has not finished
	ExitCode  int32            `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	StartedAt *types.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	StoppedAt *types.Timestamp `protobuf:"bytes,5,opt,name=stopped_at,json=stoppedAt,proto3" json:"stopped_at,omitempty"`
	Runtime   *types.Duration  `protobuf:"bytes,6,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// proc(5): "On 64-bit systems, pid_max can be set to any value up to 2^22"
	Pid                  uint32   `protobuf:"varint,7,opt,name=pid,proto3" json:"pid,omitempty"`
	Stdout               []string `protobuf:"bytes,8,rep,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr               []string `protobuf:"bytes,9,rep,name=stderr,proto3" json:"stderr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobResponse) Reset()         { *m = GetJobResponse{} }
func (m *GetJobResponse) String() string { return proto.CompactTextString(m) }
func (*GetJobResponse) ProtoMessage()    {}
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fc5f638932919ca, []int{6}
}
func (m *GetJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobResponse.Unmarshal(m, b)
}
func (m *GetJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobResponse.Marshal(b, m, deterministic)
}
func (m *GetJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobResponse.Merge(m, src)
}
func (m *GetJobResponse) XXX_Size() int {
	return xxx_messageInfo_GetJobResponse.Size(m)
}
func (m *GetJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobResponse proto.InternalMessageInfo

func (m *GetJobResponse) GetCommand() *CommandSpec {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *GetJobResponse) GetStatus() GetJobResponse_Status {
	if m != nil {
		return m.Status
	}
	return GetJobResponse_UNKNOWN
}

func (m *GetJobResponse) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *GetJobResponse) GetStartedAt() *types.Timestamp {
	if m != nil {
		return m.StartedAt
	}
	return nil
}

func (m *GetJobResponse) GetStoppedAt() *types.Timestamp {
	if m != nil {
		return m.StoppedAt
	}
	return nil
}

func (m *GetJobResponse) GetRuntime() *types.Duration {
	if m != nil {
		return m.Runtime
	}
	return nil
}

func (m *GetJobResponse) GetPid() uint32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *GetJobResponse) GetStdout() []string {
	if m != nil {
		return m.Stdout
	}
	return nil
}

func (m *GetJobResponse) GetStderr() []string {
	if m != nil {
		return m.Stderr
	}
	return nil
}

func init() {
	proto.RegisterEnum("jobworker.GetJobResponse_Status", GetJobResponse_Status_name, GetJobResponse_Status_value)
	proto.RegisterType((*CommandSpec)(nil), "jobworker.CommandSpec")
	proto.RegisterType((*StartJobRequest)(nil), "jobworker.StartJobRequest")
	proto.RegisterType((*StartJobResponse)(nil), "jobworker.StartJobResponse")
	proto.RegisterType((*StopJobRequest)(nil), "jobworker.StopJobRequest")
	proto.RegisterType((*StopJobResponse)(nil), "jobworker.StopJobResponse")
	proto.RegisterType((*GetJobRequest)(nil), "jobworker.GetJobRequest")
	proto.RegisterType((*GetJobResponse)(nil), "jobworker.GetJobResponse")
}

func init() { proto.RegisterFile("jobworker.proto", fileDescriptor_4fc5f638932919ca) }

var fileDescriptor_4fc5f638932919ca = []byte{
	// 559 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4f, 0x6f, 0xda, 0x4e,
	0x10, 0xfd, 0x39, 0x0e, 0xfe, 0x33, 0x08, 0xe2, 0xdf, 0x1e, 0x22, 0xe3, 0x48, 0x2d, 0xf2, 0x09,
	0xa9, 0xaa, 0x53, 0x91, 0x4b, 0x7b, 0xa8, 0x54, 0x0a, 0x14, 0x25, 0xa5, 0x06, 0x19, 0x10, 0x52,
	0x2f, 0xc8, 0xc6, 0x5b, 0x6a, 0x1a, 0x58, 0x77, 0xbd, 0x6e, 0xfa, 0x35, 0xfb, 0x09, 0xfa, 0x55,
	0xaa, 0xdd, 0xb5, 0x09, 0xa4, 0xb4, 0x4a, 0x4f, 0xcc, 0xbc, 0x79, 0x6f, 0x76, 0x3c, 0xf3, 0x80,
	0xb3, 0x35, 0x89, 0xee, 0x08, 0xfd, 0x82, 0xa9, 0x97, 0x52, 0xc2, 0x08, 0x32, 0x77, 0x80, 0xf3,
	0x74, 0x45, 0xc8, 0xea, 0x16, 0x5f, 0x8a, 0x42, 0x94, 0x7f, 0xba, 0x64, 0xc9, 0x06, 0x67, 0x2c,
	0xdc, 0xa4, 0x92, 0xeb, 0x3c, 0x79, 0x48, 0x88, 0x73, 0x1a, 0xb2, 0x84, 0x6c, 0x65, 0xdd, 0x5d,
	0x40, 0xb5, 0x4b, 0x36, 0x9b, 0x70, 0x1b, 0x4f, 0x52, 0xbc, 0x44, 0x36, 0xe8, 0x4b, 0x99, 0xda,
	0x4a, 0x53, 0x69, 0x99, 0x41, 0x99, 0x22, 0x04, 0xa7, 0x21, 0x5d, 0x65, 0xf6, 0x49, 0x53, 0x6d,
	0x99, 0x81, 0x88, 0x91, 0x05, 0x2a, 0xde, 0x7e, 0xb3, 0x55, 0x01, 0xf1, 0x90, 0x23, 0x71, 0x42,
	0xed, 0x53, 0xa1, 0xe5, 0xa1, 0xdb, 0x85, 0xb3, 0x09, 0x0b, 0x29, 0xbb, 0x21, 0x51, 0x80, 0xbf,
	0xe6, 0x38, 0x63, 0xe8, 0xc5, 0xe1, 0x23, 0xd5, 0xf6, 0xb9, 0x77, 0xff, 0x89, 0x7b, 0xd3, 0xec,
	0x1e, 0x77, 0x9f, 0x83, 0x75, 0xdf, 0x24, 0x4b, 0xc9, 0x36, 0xc3, 0xa8, 0x01, 0xc6, 0x9a, 0x44,
	0x8b, 0x3c, 0x4f, 0x76, 0xb3, 0xae, 0x49, 0x34, 0xcb, 0x93, 0xd8, 0x7d, 0x06, 0xf5, 0x09, 0x23,
	0xe9, 0xde, 0x93, 0x7f, 0x21, 0xff, 0xcf, 0x07, 0x2c, 0xc8, 0xb2, 0xb5, 0x3b, 0x80, 0xda, 0x00,
	0xb3, 0x47, 0xc9, 0xd1, 0x05, 0x98, 0x77, 0x09, 0xfb, 0xbc, 0xb8, 0x25, 0x62, 0x39, 0x4a, 0xcb,
	0x08, 0x0c, 0x0e, 0x0c, 0xc9, 0x2a, 0x73, 0x7f, 0xaa, 0x50, 0x2f, 0x3b, 0x15, 0x63, 0xff, 0xf3,
	0xc7, 0xa3, 0x97, 0xa0, 0x65, 0x2c, 0x64, 0xb9, 0x6c, 0x5f, 0x6f, 0x37, 0xf7, 0x04, 0x87, 0xcd,
	0xbd, 0x89, 0xe0, 0x05, 0x05, 0x9f, 0xcf, 0x86, 0xbf, 0x27, 0x6c, 0xb1, 0x24, 0x31, 0xb6, 0xd5,
	0xa6, 0xd2, 0xaa, 0x04, 0x06, 0x07, 0xba, 0x24, 0xc6, 0xe8, 0x15, 0x40, 0xc6, 0x77, 0x8a, 0xe3,
	0x45, 0xc8, 0xc4, 0xc5, 0xaa, 0x6d, 0xc7, 0x93, 0x76, 0xf1, 0x4a, 0xbb, 0x78, 0xd3, 0xd2, 0x4f,
	0x81, 0x59, 0xb0, 0x3b, 0x4c, 0x4a, 0x49, 0x9a, 0x4a, 0x69, 0xe5, 0x31, 0x52, 0xc1, 0xee, 0x30,
	0x74, 0x05, 0x3a, 0xcd, 0xb7, 0xdc, 0xa5, 0xb6, 0x26, 0x74, 0x8d, 0xdf, 0x74, 0xbd, 0xc2, 0xa1,
	0x41, 0xc9, 0xe4, 0xae, 0x4a, 0x93, 0xd8, 0xd6, 0x9b, 0x4a, 0xab, 0x16, 0xf0, 0x10, 0x9d, 0xf3,
	0x9d, 0xc4, 0x24, 0x67, 0xb6, 0x21, 0xcc, 0x57, 0x64, 0x05, 0x8e, 0x29, 0xb5, 0xcd, 0x1d, 0x8e,
	0x29, 0x75, 0xe7, 0xa0, 0xc9, 0xdd, 0xa0, 0x2a, 0xe8, 0x33, 0xff, 0xbd, 0x3f, 0x9a, 0xfb, 0xd6,
	0x7f, 0x3c, 0x09, 0x66, 0xbe, 0x7f, 0xed, 0x0f, 0x2c, 0x05, 0xd5, 0xc0, 0xec, 0x8e, 0x3e, 0x8c,
	0x87, 0xfd, 0x69, 0xbf, 0x67, 0x9d, 0xf0, 0xda, 0x64, 0x3a, 0x1a, 0x8f, 0xfb, 0x3d, 0x4b, 0x45,
	0x00, 0xda, 0xbb, 0xce, 0xf5, 0xb0, 0xdf, 0xb3, 0x4e, 0x79, 0x61, 0xdc, 0xf7, 0x7b, 0x5c, 0x54,
	0x69, 0xff, 0x50, 0xc0, 0xbc, 0x21, 0xd1, 0x5c, 0x9c, 0x03, 0x75, 0xc1, 0x28, 0x7d, 0x8a, 0x9c,
	0xbd, 0x33, 0x3d, 0xf8, 0x07, 0x38, 0x17, 0x47, 0x6b, 0x85, 0x43, 0xde, 0x80, 0x5e, 0x18, 0x12,
	0x35, 0x0e, 0x78, 0xfb, 0x8e, 0x76, 0x9c, 0x63, 0xa5, 0xa2, 0xc3, 0x6b, 0xd0, 0xa4, 0x31, 0x90,
	0x7d, 0xc4, 0x2b, 0x52, 0xdf, 0xf8, 0xa3, 0x8b, 0xde, 0xea, 0x1f, 0x2b, 0xf2, 0x18, 0x9a, 0xf8,
	0xb9, 0xfa, 0x15, 0x00, 0x00, 0xff, 0xff, 0x20, 0xd6, 0x65, 0x01, 0x82, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JobWorkerClient is the client API for JobWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobWorkerClient interface {
	StartJob(ctx context.Context, in *StartJobRequest, opts ...grpc.CallOption) (*StartJobResponse, error)
	StopJob(ctx context.Context, in *StopJobRequest, opts ...grpc.CallOption) (*StopJobResponse, error)
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
}

type jobWorkerClient struct {
	cc *grpc.ClientConn
}

func NewJobWorkerClient(cc *grpc.ClientConn) JobWorkerClient {
	return &jobWorkerClient{cc}
}

func (c *jobWorkerClient) StartJob(ctx context.Context, in *StartJobRequest, opts ...grpc.CallOption) (*StartJobResponse, error) {
	out := new(StartJobResponse)
	err := c.cc.Invoke(ctx, "/jobworker.JobWorker/StartJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobWorkerClient) StopJob(ctx context.Context, in *StopJobRequest, opts ...grpc.CallOption) (*StopJobResponse, error) {
	out := new(StopJobResponse)
	err := c.cc.Invoke(ctx, "/jobworker.JobWorker/StopJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobWorkerClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	out := new(GetJobResponse)
	err := c.cc.Invoke(ctx, "/jobworker.JobWorker/GetJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobWorkerServer is the server API for JobWorker service.
type JobWorkerServer interface {
	StartJob(context.Context, *StartJobRequest) (*StartJobResponse, error)
	StopJob(context.Context, *StopJobRequest) (*StopJobResponse, error)
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
}

// UnimplementedJobWorkerServer can be embedded to have forward compatible implementations.
type UnimplementedJobWorkerServer struct {
}

func (*UnimplementedJobWorkerServer) StartJob(ctx context.Context, req *StartJobRequest) (*StartJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartJob not implemented")
}
func (*UnimplementedJobWorkerServer) StopJob(ctx context.Context, req *StopJobRequest) (*StopJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopJob not implemented")
}
func (*UnimplementedJobWorkerServer) GetJob(ctx context.Context, req *GetJobRequest) (*GetJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJob not implemented")
}

func RegisterJobWorkerServer(s *grpc.Server, srv JobWorkerServer) {
	s.RegisterService(&_JobWorker_serviceDesc, srv)
}

func _JobWorker_StartJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobWorkerServer).StartJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jobworker.JobWorker/StartJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobWorkerServer).StartJob(ctx, req.(*StartJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobWorker_StopJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobWorkerServer).StopJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jobworker.JobWorker/StopJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobWorkerServer).StopJob(ctx, req.(*StopJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobWorker_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobWorkerServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jobworker.JobWorker/GetJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobWorkerServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JobWorker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jobworker.JobWorker",
	HandlerType: (*JobWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartJob",
			Handler:    _JobWorker_StartJob_Handler,
		},
		{
			MethodName: "StopJob",
			Handler:    _JobWorker_StopJob_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _JobWorker_GetJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jobworker.proto",
}
