// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	server "github.com/andrejtokarcik/jobworker/server"
	mock "github.com/stretchr/testify/mock"
)

// CmdCreator is an autogenerated mock type for the CmdCreator type
type CmdCreator struct {
	mock.Mock
}

// NewCmd provides a mock function with given fields: dir, env, name, args
func (_m *CmdCreator) NewCmd(dir string, env []string, name string, args []string) server.Cmd {
	ret := _m.Called(dir, env, name, args)

	var r0 server.Cmd
	if rf, ok := ret.Get(0).(func(string, []string, string, []string) server.Cmd); ok {
		r0 = rf(dir, env, name, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(server.Cmd)
		}
	}

	return r0
}
