// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	proto "github.com/andrejtokarcik/jobworker/proto"
	mock "github.com/stretchr/testify/mock"

	server "github.com/andrejtokarcik/jobworker/server"
)

// CmdCreator is an autogenerated mock type for the CmdCreator type
type CmdCreator struct {
	mock.Mock
}

// NewCmd provides a mock function with given fields: _a0
func (_m *CmdCreator) NewCmd(_a0 *proto.CommandSpec) server.Cmd {
	ret := _m.Called(_a0)

	var r0 server.Cmd
	if rf, ok := ret.Get(0).(func(*proto.CommandSpec) server.Cmd); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(server.Cmd)
		}
	}

	return r0
}
