// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"

	pkix "crypto/x509/pkix"
)

// RPCCallerFilter is an autogenerated mock type for the RPCCallerFilter type
type RPCCallerFilter struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *RPCCallerFilter) Execute(_a0 pkix.Name, _a1 *grpc.UnaryServerInfo) bool {
	ret := _m.Called(_a0, _a1)

	var r0 bool
	if rf, ok := ret.Get(0).(func(pkix.Name, *grpc.UnaryServerInfo) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
